name: Say hello
on:
  push:
    branches:
      - main
jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Juan"


      - name: Dime la fecha
        run: date
      - run: ls -l
            
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint

      - name: Dime la fecha
        run: date
      - name: List Directory
        run: ls -l